package generate

var ErrorCodeFormat = `
// Code generated by go-easy generate error code DO NOT EDIT.
// go-easy url: https://github.com/siskinc/go-easy
package {{ .package }}

func (e {{ .error_type }}) Error() string {
	switch e {
	{{ range $name, $doc := .error_info }}
	case {{ $name }}:
		return "{{ $doc }}"
	{{ end }}
	}
	return "UNKNOWN"
}

func (e {{ .error_type }}) String() string {
	switch e {
	{{ range $name, $doc := .error_info }}
	case {{ $name }}:
		return "{{ $name }}"
	{{ end }}
	}
	return "UNKNOWN"
}

`
